//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InBed.Service.CompanionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.cxfapp.bnc.org/", ConfigurationName="CompanionService.BusinessProcess")]
    public interface BusinessProcess {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        InBed.Service.CompanionService.SendRequestResponse SendRequest(InBed.Service.CompanionService.SendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<InBed.Service.CompanionService.SendRequestResponse> SendRequestAsync(InBed.Service.CompanionService.SendRequest request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        InBed.Service.CompanionService.GetSleepDataResponse GetSleepData(InBed.Service.CompanionService.GetSleepData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<InBed.Service.CompanionService.GetSleepDataResponse> GetSleepDataAsync(InBed.Service.CompanionService.GetSleepData request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendRequest", Namespace="http://ws.cxfapp.bnc.org/", Order=0)]
        public InBed.Service.CompanionService.SendRequestBody Body;
        
        public SendRequest() {
        }
        
        public SendRequest(InBed.Service.CompanionService.SendRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SendRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public SendRequestBody() {
        }
        
        public SendRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendRequestResponse", Namespace="http://ws.cxfapp.bnc.org/", Order=0)]
        public InBed.Service.CompanionService.SendRequestResponseBody Body;
        
        public SendRequestResponse() {
        }
        
        public SendRequestResponse(InBed.Service.CompanionService.SendRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SendRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public SendRequestResponseBody() {
        }
        
        public SendRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSleepData {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSleepData", Namespace="http://ws.cxfapp.bnc.org/", Order=0)]
        public InBed.Service.CompanionService.GetSleepDataBody Body;
        
        public GetSleepData() {
        }
        
        public GetSleepData(InBed.Service.CompanionService.GetSleepDataBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetSleepDataBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public GetSleepDataBody() {
        }
        
        public GetSleepDataBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSleepDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSleepDataResponse", Namespace="http://ws.cxfapp.bnc.org/", Order=0)]
        public InBed.Service.CompanionService.GetSleepDataResponseBody Body;
        
        public GetSleepDataResponse() {
        }
        
        public GetSleepDataResponse(InBed.Service.CompanionService.GetSleepDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetSleepDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public GetSleepDataResponseBody() {
        }
        
        public GetSleepDataResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BusinessProcessChannel : InBed.Service.CompanionService.BusinessProcess, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusinessProcessClient : System.ServiceModel.ClientBase<InBed.Service.CompanionService.BusinessProcess>, InBed.Service.CompanionService.BusinessProcess {
        
        public BusinessProcessClient() {
        }
        
        public BusinessProcessClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusinessProcessClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessProcessClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessProcessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InBed.Service.CompanionService.SendRequestResponse InBed.Service.CompanionService.BusinessProcess.SendRequest(InBed.Service.CompanionService.SendRequest request) {
            return base.Channel.SendRequest(request);
        }
        
        public string SendRequest(string arg0) {
            InBed.Service.CompanionService.SendRequest inValue = new InBed.Service.CompanionService.SendRequest();
            inValue.Body = new InBed.Service.CompanionService.SendRequestBody();
            inValue.Body.arg0 = arg0;
            InBed.Service.CompanionService.SendRequestResponse retVal = ((InBed.Service.CompanionService.BusinessProcess)(this)).SendRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InBed.Service.CompanionService.SendRequestResponse> InBed.Service.CompanionService.BusinessProcess.SendRequestAsync(InBed.Service.CompanionService.SendRequest request) {
            return base.Channel.SendRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<InBed.Service.CompanionService.SendRequestResponse> SendRequestAsync(string arg0) {
            InBed.Service.CompanionService.SendRequest inValue = new InBed.Service.CompanionService.SendRequest();
            inValue.Body = new InBed.Service.CompanionService.SendRequestBody();
            inValue.Body.arg0 = arg0;
            return ((InBed.Service.CompanionService.BusinessProcess)(this)).SendRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InBed.Service.CompanionService.GetSleepDataResponse InBed.Service.CompanionService.BusinessProcess.GetSleepData(InBed.Service.CompanionService.GetSleepData request) {
            return base.Channel.GetSleepData(request);
        }
        
        public string GetSleepData(string arg0) {
            InBed.Service.CompanionService.GetSleepData inValue = new InBed.Service.CompanionService.GetSleepData();
            inValue.Body = new InBed.Service.CompanionService.GetSleepDataBody();
            inValue.Body.arg0 = arg0;
            InBed.Service.CompanionService.GetSleepDataResponse retVal = ((InBed.Service.CompanionService.BusinessProcess)(this)).GetSleepData(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InBed.Service.CompanionService.GetSleepDataResponse> InBed.Service.CompanionService.BusinessProcess.GetSleepDataAsync(InBed.Service.CompanionService.GetSleepData request) {
            return base.Channel.GetSleepDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<InBed.Service.CompanionService.GetSleepDataResponse> GetSleepDataAsync(string arg0) {
            InBed.Service.CompanionService.GetSleepData inValue = new InBed.Service.CompanionService.GetSleepData();
            inValue.Body = new InBed.Service.CompanionService.GetSleepDataBody();
            inValue.Body.arg0 = arg0;
            return ((InBed.Service.CompanionService.BusinessProcess)(this)).GetSleepDataAsync(inValue);
        }
    }
}
